services:

  db:
    container_name: blog-postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: rafal
      POSTGRES_PASSWORD: rafal
      POSTGRES_DB: blog-app
      PGDATA: /data/postgres
    volumes:
      - blog-db:/data/postgres
    ports:
      - "8081:5432"

  pgAdmin:
    image: dpage/pgadmin4:7.1
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rafal@blog-app.com
      PGADMIN_DEFAULT_PASSWORD: rafal

volumes:
  blog-db: